[Dev to stage merge] mobile
Educado-App/educado-mobile pull request #133
Opened 2023-10-27 11:30 UTC by sofiiagran

## Description

Added explore page and navbar. 
Added exercise screen.

## Changes

Created the explore page and changed the navigation bar.
Now user can subscribe from the explore page and is then redirected to the course.

Added exercise screen.

## Related Issues

PBI: I want to subscribe to the courses I'm interested in
PBI: I want to see all available courses
PBI: I want to filter courses based on category

## Checklist

- [x] Code has been tested locally and passes all relevant tests.
- [x] Documentation has been updated to reflect the changes, if applicable.
- [x] Code follows the established coding style and guidelines of the project.
- [x] All new and existing tests related to the changes have passed.
- [x] Any necessary dependencies or new packages have been properly documented.
- [x] Pull request title and description are clear and descriptive.
- [x] Reviewers have been assigned to the pull request.
- [x] Any potential security implications have been considered and addressed.
- [x] Performance impact of the changes has been evaluated, if relevant.

## Screenshots (if applicable)

<img width="100" alt="Skærmbillede 2023-10-24 kl  15 32 12" src="https://github.com/Educado-App/educado-mobile/assets/92582321/41e9ff5f-c9aa-4ddb-917d-433176cd1316">
<img width="100" alt="Skærmbillede 2023-10-23 kl  10 35 32" src="https://github.com/Educado-App/educado-mobile/assets/92582321/0fb75a83-2660-4a81-aa50-5299df716268">
<img width="100" alt="Skærmbillede 2023-10-24 kl  15 32 19" src="https://github.com/Educado-App/educado-mobile/assets/92582321/25d1f2d5-052e-4558-aeef-fee8f9bb0a45">
<img width="100" alt="Skærmbillede 2023-10-23 kl  10 35 55" src="https://github.com/Educado-App/educado-mobile/assets/92582321/749a33d3-f78f-472a-930f-074b0c2f8341">
<img width="100" alt="Screenshot 2023-10-25 at 09 49 52" src="https://github.com/Educado-App/educado-mobile/assets/76952323/bdadf1ef-06e0-49b5-b4ad-731201af1a5a">

## If mobile/frontend pull request, what version of the backend is it stable, and running on? 

Works with staging backend.

Use production database and log in with Ola.lola@mail.dk with pass: Password 

## Notes for Reviewers

All storage services and APIs have been tested, so we are sure they are loading correctly.

All utility functions are also tested.

2023-10-27 11:55 UTC, PrometheusBork commented on eml/assets/images/dots-horizontal.png
Is this used anywhere? or will it be used in the future?

2023-10-27 11:56 UTC, PrometheusBork commented on eml/components/exercise/LeaveButton.js
> +          color='#383838'
Hardcoded color

2023-10-27 11:56 UTC, PrometheusBork commented on eml/components/exercise/Progressbar.js
> +        unfilledColor='rgba(228, 242, 245, 1)'
Hardcoded colors

2023-10-27 11:58 UTC, PrometheusBork commented on eml/components/explore/CustomRating.jsx
> +        <Text className="pl-1 text-xs" style={{ color: "gray" }}>no ratings yet</Text>
Used style={} instead of nativewind for color

2023-10-27 12:43 UTC, Muad3 commented on eml/App.js
har du ikke removet homestack her men stadig tager den i brug?

2023-10-27 12:52 UTC, sofiiagran commented on eml/components/exercise/LeaveButton.js
> +          color='#383838'
@Andazu @amaliedilling

2023-10-27 13:09 UTC, Muad3 reviewed
jeg er enig med Toby's comments ellers fint

2023-10-27 18:11 UTC, MortenMunk requested changes
Does this pass github checks? I don't see any checks on this 😢

2023-10-30 14:18 UTC, sofiiagran reviewed
Everything should be fixed and I will trigger GitHub actions

2023-10-31 06:59 UTC, sofiiagran commented
Github action passed, please re-review

2023-10-31 07:38 UTC, PrometheusBork reviewed
Almost everything looks good, but for some reason the exercise screen crashes the backend and receives an error. Is this a known error or was some data deleted from the database? Can't really approve before this is clarified

2023-10-31 07:38 UTC, PrometheusBork submitted a review, later dismissed

2023-10-31 08:40 UTC, sofiiagran commented
@PrometheusBork it only works on docker... the production database has been reset and stuff is gone.

I will make an update tomorrow where it makes sense with the new data from the database

2023-10-31 08:53 UTC, PrometheusBork commented
> @PrometheusBork it only works on docker... the production database has been reset and stuff is gone.
> 
> I will make an update tomorrow where it makes sense with the new data from the database
> 
> I can hardcode it so it works...?

If it works with docker then I can just approve it 👍

2023-10-31 08:54 UTC, PrometheusBork approved these changes
Good Work!

2023-10-31 11:19 UTC, MortenMunk requested changes
Overall it looks fine, but I have a few points:
- considering this PR contains 62 changed files, i think the **changes** section was extremely short, and did not provide a great overview of changes, hence i posted a lot of questions for this PR.
- Some colors are hardcoded and not using the tailwind colors we have specified, which makes me sad, as these colors would have to be changed manually if we decide to change the theme 😢 
- A lot of lines were deleted from the files, but I realized that some of these lines were moved to other files as modules, which is okay, so some of my comments may just be resolved.

Once these things has been adressed, I think it looks fine 👍🥇

2023-10-31 11:19 UTC, MortenMunk commented on eml/screens/courses/CourseScreen.jsx
I assume this is deleted on purpose?

2023-10-31 11:19 UTC, MortenMunk commented on eml/screens/excercise/ExerciseScreen.jsx
Consider what to do with all the outcommented stuff

2023-10-31 11:19 UTC, MortenMunk commented on eml/screens/profile/ProfileSettings.js
This is deleted on purpose i guess?

2023-10-31 11:19 UTC, MortenMunk commented on eml/test/components/login/EnterNewPasswordScreen.test.js
A lot has been removed from this test file, which is a shame 😢 but I assume this is on purpose?

2023-10-31 12:21 UTC, sofiiagran commented on eml/screens/excercise/ExerciseScreen.jsx
@amaliedilling @Andazu

2023-10-31 12:24 UTC, sofiiagran commented on eml/screens/courses/CourseScreen.jsx
@MortenMunk it is not deleted on my computer? Are you thinking about ExerciseScreen? and exerciseScreen are not deleted, just changed from js to jsx

2023-10-31 12:24 UTC, sofiiagran commented on eml/App.js
@MortenMunk

2023-10-31 12:25 UTC, sofiiagran commented on eml/components/exercise/ExerciseButtons.jsx
ask @Andazu @amaliedilling

2023-10-31 12:25 UTC, sofiiagran commented on eml/components/exercise/LeaveButton.js
> +          color='#383838'
@Andazu @amaliedilling

2023-10-31 12:26 UTC, sofiiagran commented on eml/components/exercise/Progressbar.js
> +        color='rgba(94, 204, 233, 1)'
@Andazu @amaliedilling

2023-10-31 12:35 UTC, MortenMunk commented on eml/screens/courses/CourseScreen.jsx
> @MortenMunk it is not deleted on my computer? Are you thinking about ExerciseScreen? and exerciseScreen are not deleted, just changed from js to jsx

Yes, sorry.. I meant a lot of this file is deleted, but I guess it is moved to utility function instead? then it is okay 👍

2023-10-31 12:45 UTC, Andazu commented on eml/components/exercise/LeaveButton.js
> +          color='#383838'
ok, im do now

2023-10-31 13:06 UTC, Andazu commented on eml/components/exercise/LeaveButton.js
> +          color='#383838'
This has been committed to the branch

2023-10-31 13:27 UTC, sofiiagran commented on eml/screens/excercise/ExerciseScreen.jsx
I think the code can be kept for now, and when we look into how to navigate between exercises maybe it can be used. However, after navigation is created, it will either be removed or used. @MortenMunk

2023-10-31 14:01 UTC, MaizeHH approved these changes
Looks good 👍

2023-10-31 14:41 UTC, MortenMunk approved these changes
Looks good now, great job @sofiiagran 👍 🥇

2023-10-31 14:41 UTC, merged