Dev to stage [IMPORTANT]
Educado-App/educado-mobile pull request #178
Opened 2023-11-13 13:27 UTC by MortenMunk

## Description

👏 Finally, I am able to present to you, a dev branch that should resemble staging, and a few added features such as linting, toast notifications, updated endpoints, refactors etc.

## Changes

- made urls in userApi.js and api.js identical to staging
- linting added to config files
- linting added to tests
- 

## Related Issues

List any related issues or tickets that this pull request addresses or resolves.

## Checklist

- [ ] Code has been tested locally and passes all relevant tests.
- [ ] Documentation has been updated to reflect the changes, if applicable.
- [ ] Code follows the established coding style and guidelines of the project.
- [ ] All new and existing tests related to the changes have passed.
- [ ] Any necessary dependencies or new packages have been properly documented.
- [ ] Pull request title and description are clear and descriptive.
- [ ] Reviewers have been assigned to the pull request.
- [ ] Any potential security implications have been considered and addressed.
- [ ] Performance impact of the changes has been evaluated, if relevant.

## Screenshots (if applicable)

Insert screenshots or gifs that visually demonstrate the changes made in this pull request.

## If mobile/frontend pull request, what version of the backend is it stable, and running on? 

Please provide information on what BACKEND branch and what BACKEND commit id this mobile/frontend Pull Request is stable on for reviewers.

Commit id can be found under branch --> commits. 

Example:

Branch: staging

Commit id: f0013e8

## Notes for Reviewers

Provide any additional information that could be useful for reviewers. This could include context about the problem being solved, implementation details, or anything else that might aid in the review process.

2023-11-13 17:24 UTC, PrometheusBork commented
I have encountered 2 errors: 
1. When I have subscribed to a course and go to explore page it will show correctly that I am subscribed to fx "Financas Pessoais" but if I set filter to costura it will say i am subscribed to "Virtual Tutor Test"
2. The video doesn't work for me idk if that is a big problem right now, there is also a problem if you swipe too fast in lecturescreen, as you will basically break it.

2023-11-14 13:25 UTC, PrometheusBork approved these changes
It works fine for me, there are minor bugs though but it will be fixed in future pull requests. I think it is more important to get stage stable. Tested this with Staging backend btw

2023-11-14 13:35 UTC, sofiiagran requested changes
See my comments :))

+ ask @BenjaminVilladsen to fix the unique key thing, I believe it was directly committed to staging and therefore does not exist in this PR ...

2023-11-14 13:35 UTC, sofiiagran commented on eml/components/exercise/LeaveButton.js
it replaces tailwind with hardcoded colors

2023-11-14 13:35 UTC, sofiiagran commented on eml/components/explore/CustomRating.jsx
again replace tailwind config with hardcoded colors

2023-11-14 13:35 UTC, sofiiagran commented on eml/components/login/RegisterForm.js
>      try {
try {
      await registerUser(obj)
        .then(async function (response) {
          // saves input information locally
          await saveUserInfoLocally(response._id, firstName, lastName, email);
          await AsyncStorage.setItem(USER_ID, response._id);
        }).then(async function () {
        .then(async function () {
          // logs in the user, if no errors occur, navigates to home screen and sets token
          await loginFromRegister(obj);
        }) 

keep this from staging!!! It was a hotfix from the user test

2023-11-14 13:35 UTC, sofiiagran commented on eml/components/profileSettings/changeEmailButton.js
why not call it from StorageService?

2023-11-14 13:35 UTC, sofiiagran commented on eml/components/profileSettings/changeFirstNameButton.js
Why not call from StorageService?

2023-11-14 13:35 UTC, sofiiagran commented on eml/components/profileSettings/changeLastNameButton.js
Why not call from StorageService?

2023-11-14 13:35 UTC, sofiiagran commented on eml/package.json
> -    "build": "eas build -p android --profile preview",
keep this from staging:     "build": "eas build -p android --profile preview",

2023-11-14 14:10 UTC, amaliedilling requested changes
made some comments, pls have a look :))

2023-11-14 14:10 UTC, amaliedilling commented on eml/services/StorageService.js
>    const fetchedUserInfo = JSON.parse(await AsyncStorage.getItem(USER_INFO));
this should still have some type of error handling, no?

2023-11-14 14:10 UTC, amaliedilling commented on eml/App.js
we (gamified) use the ErrorScreen, but it should not be in the WelcomeStack

2023-11-15 09:18 UTC, carlryskov commented on eml/components/explore/CustomRating.jsx
We fix the key issues with our next PR

2023-11-15 09:18 UTC, PrometheusBork commented on eml/screens/profile/Profile.js
> -      const fetchedProfile = await getUserInfo();
Again why are we not using getuserinfo from storageservice

2023-11-15 09:20 UTC, carlryskov approved these changes
The Video streaming related files look good for now. "Key" warning will be fixed once this PR is merged, and we can merge our own latest PR with necessary changes.

2023-11-15 09:21 UTC, Donhusum commented on eml/api/api.js
I have reimplemented the error handling that was removed. I also removed a console log, and added a comment.

2023-11-15 09:33 UTC, Donhusum commented on eml/api/userApi.js
>      email: ${obj.email ?? 'undefined'}`);
Added uniform error handling to all functions in userApi

2023-11-15 11:18 UTC, amaliedilling approved these changes

2023-11-15 11:19 UTC, sofiiagran approved these changes
I fixed my fixes

2023-11-15 14:04 UTC, ITPini approved these changes

2023-11-15 14:26 UTC, merged