Video uservalidation
Educado-App/educado-mobile pull request #184
Opened 2023-11-15 09:43 UTC by Mikkelmmc

## Description

Minor adjustments that meet user validation requirements.

## Changes

Fixed
- Translations
- Hardcoded stuff in home screen

Added
- Description to iconheader

## Checklist

- [x] Code has been tested locally and passes all relevant tests.
- [x] Documentation has been updated to reflect the changes, if applicable.
- [x] Code follows the established coding style and guidelines of the project.
- [x] All new and existing tests related to the changes have passed.
- [x] Any necessary dependencies or new packages have been properly documented.
- [x] Pull request title and description are clear and descriptive.
- [x] Reviewers have been assigned to the pull request.
- [x] Any potential security implications have been considered and addressed.
- [x] Performance impact of the changes has been evaluated, if relevant.

## Screenshots
<img width="200" alt="Skærmbillede 2023-11-15 kl  10 27 32" src="https://github.com/Educado-App/educado-mobile/assets/41455260/2758d8c7-59ae-4e03-b401-adbc95f28220">
<img width="200" alt="Skærmbillede 2023-11-15 kl  10 28 09" src="https://github.com/Educado-App/educado-mobile/assets/41455260/1e3417a9-9ed4-4c45-8ca8-32abb2dfcd81">
<img width="200" alt="Skærmbillede 2023-11-15 kl  10 29 19" src="https://github.com/Educado-App/educado-mobile/assets/41455260/56598e7d-795f-403f-968b-62562bbbb028">

## If mobile/frontend pull request, what version of the backend is it stable, and running on? 

Backend: dev

Branch: dev
Commit id: 54ad44e776fdeeac64203a3fc23efe273b2d40e5

2023-11-15 10:45 UTC, JackSMunn approved these changes
Approved, not tested locally though, so make sure it works on other computers than your own before merging

2023-11-15 19:21 UTC, sofiiagran approved these changes
Smukt <3

2023-11-16 09:41 UTC, ITPini approved these changes

2023-11-16 10:13 UTC, PrometheusBork requested changes
Looks and works fine just a single small fix and i'll approve

2023-11-16 10:13 UTC, PrometheusBork commented on eml/components/general/IconHeader.jsx
> +                source={require('../../assets/singleIcon.png')}
The path here is not correct, it should be "require('../../assets/images/singleIcon.png')"

2023-11-16 10:16 UTC, sofiiagran requested changes
See @PrometheusBork comment, everything else is good

2023-11-16 12:22 UTC, sofiiagran approved these changes
nice

2023-11-16 12:31 UTC, PrometheusBork approved these changes
Very nice very good I like

2023-11-16 12:31 UTC, merged