[App - Certificate] Download certificate #305
Educado-App/educado-mobile pull request #351
Opened 2024-11-06 10:54 UTC by LucaPurcilly

## Description

This PR adds functionality for users to download their certificates as PDF.
It also adds functionality for certificates to be automatically completed on course completion.

## Changes

We have fixed the api service for downloading and generating certificates, and have used Expo file system to manage storage of the actual pdf file.

## Related Issues

Fixes #305 

## Checklist

- [ ] Code has been tested locally and passes all relevant tests.
- [ ] Documentation has been updated to reflect the changes, if applicable.
- [ ] Code follows the established coding style and guidelines of the project.
- [ ] All new and existing tests related to the changes have passed.
- [ ] Any necessary dependencies or new packages have been properly documented.
- [ ] Pull request title and description are clear and descriptive.
- [ ] Reviewers have been assigned to the pull request.
- [ ] Any potential security implications have been considered and addressed.
- [ ] Performance impact of the changes has been evaluated, if relevant.
- [ ] Changes have been approved by Product Owner
- [ ] Code has been analyzed with CodeScene
- [ ] I have reviewed the pull request myself

## Screenshots (if applicable)

![ezgif-5-5681a1cde3](https://github.com/user-attachments/assets/093b21de-bbc8-4330-8c40-1b16819d2096)

## If mobile/frontend pull request, what version of the backend is it stable, and running on? 

Please provide information on what BACKEND branch and what BACKEND commit id this mobile/frontend Pull Request is stable on for reviewers.

The download certificate functionality relies on a change made to the certificate service. Currently this is in the staging branch, but deployment has failed.

## Notes for Reviewers

If testing this manually, you must run the latest staging version of the certificate service locally.

2024-11-06 13:52 UTC, Laskiri commented on eml/services/utilityFunctions.js
remove console.log here perhaps

2024-11-06 13:58 UTC, Laskiri commented on eml/components/certificate/CertificateCard.jsx
I think perhaps instead of making certificateURL an exported variable from api and importing it here,we can import it from env instead or is there a particular reason for doing it like this?

2024-11-06 14:01 UTC, Laskiri commented on eml/components/certificate/CertificateCard.jsx
Also we need propTypes in order to comply with CI, perhapsj just make dateofcompletion  a hardcoded value for now  around the certificates and remove it from the shape as i think, thats the property that causes the crash for some reason.

2024-11-06 18:46 UTC, Risobak requested changes
Looks good! Once Laskiri's suggestions have been resolved, I will approve :)

2024-11-06 19:43 UTC, BabaWolo commented on eml/components/certificate/CertificateCard.jsx
This is a temporary fix due to certain errors... we left a message in your group on discord

2024-11-06 19:44 UTC, BabaWolo commented on eml/components/certificate/CertificateCard.jsx
Good idea 👍🏼

2024-11-06 19:51 UTC, madsWesth submitted a review, later dismissed

2024-11-06 19:51 UTC, madsWesth commented on package.json
Install dependencies in the main package.json

2024-11-06 19:51 UTC, madsWesth commented on eml/test/components/certificate/GenerateCertitifcate.test.js
all tests commented out 🫤

2024-11-06 19:51 UTC, madsWesth commented on eml/components/certificate/CertificateCard.jsx
> +	// };
Disabling these gives linting errors so they should be fixed before merging

2024-11-06 19:51 UTC, madsWesth commented on eml/components/certificate/CertificateOverlay.jsx
> +	// };
same as other comment

2024-11-06 19:51 UTC, madsWesth commented on eml/components/certificate/CertificateTemplate.jsx
> +	// };
same as other places

2024-11-06 19:51 UTC, madsWesth commented on eml/api/api.js
> +		console.log(object);
leftover code should be removed

2024-11-06 19:51 UTC, madsWesth commented on eml/test/components/certificate/GenerateCertitifcate.test.js
These can be delayed for now and done later. No worries

2024-11-06 19:52 UTC, madsWesth commented
Otherwise looks good 👍

2024-11-07 12:18 UTC, Laskiri submitted a review, later dismissed
fix the typo so downloading works again and you can merge into dev

2024-11-07 12:18 UTC, Laskiri commented on eml/components/certificate/CertificateCard.jsx
need to fix typo CETIFICATE_URL  --> CERTIFICATE_URL , then its good to go :D!

2024-11-07 12:41 UTC, merged