Gamified edit profile merge
Educado-App/educado-mobile pull request #39
Opened 2023-10-02 07:38 UTC by benceisonline

https://github.com/orgs/Educado-App/projects/9/views/1?pane=issue&itemId=38245872

2023-10-02 19:13 UTC, loui981c requested changes
det er mest småting

2023-10-02 19:13 UTC, loui981c commented on eml/components/profileSettings/changeEmailButton.js
> +              {isLoading ? ( // Conditional rendering based on loading state
kommentaren er lidt malplaceret, da ingen kommentar de andre steder hvor conditional rendering bliver brugt

2023-10-02 19:13 UTC, loui981c commented on eml/components/profileSettings/changeFirstNameButton.js
> +  }, [courses]);*/
skal det her blive brugt senere?

2023-10-02 19:13 UTC, loui981c commented on eml/components/profileSettings/changeLastNameButton.js
> +  }, [courses]);*/
same as before

2023-10-02 19:13 UTC, loui981c commented on eml/screens/profile/ProfileSettings.js
> +  }, [courses]);*/
again:)

2023-10-02 19:13 UTC, loui981c commented on eml/services/StorageService.js
> +};
bliver det her brugt på jeres screen?

2023-10-02 19:13 UTC, loui981c commented on eml/services/StorageService.js
> +}
nysgerrig over de her funktioner ift jeres PBI

2023-10-02 19:13 UTC, loui981c commented on eml/tailwind.config.js
> +        'montserrat': 'Montserrat-Regular',
montserrat behøver ikke at være i '' og det ville nok give fejl for os andre:)

2023-10-03 07:38 UTC, benceisonline commented on eml/services/StorageService.js
> +};
vi har ikke rørt ved storageservice, github er wonky

2023-10-03 07:39 UTC, benceisonline commented on eml/services/StorageService.js
> +}
Vi har ikke rørt ved storageservice, github er wonky. Lad være med at slette tho, det er også med i main.

2023-10-03 07:55 UTC, loui981c approved these changes

2023-10-03 08:31 UTC, merged