Cert 2
Educado-App/educado-mobile pull request #40
Opened 2023-10-03 08:46 UTC by Jatewo

## Description

Fixed errors related to login and made functionality for creating and checking login tokens.

## Changes

- Removed setPassword("") from login function
- Added functionality for setting login token upon succesful login
- Checks for login
  - Login page redirects to home page if token is already present (user is already logged in)
  - All other pages redirects to login page if no token is present (user is not logged in)
- Removed unused leftover code
- Added component for popup alerts
- Added helper function for removing emojis from password input
- Added component for alerts in form fields
- Refactored login and register forms to use the alert component
- Fixed error handling when logging in (shows error for wrong email and password)
- Relevant tests for login and register screens and components

## Related Issues

#### #25 - Dependency on Authentication:
Token and user info are saved in AsyncStorage. User info might need changes in the backend in order to send the needed information.

## Checklist

- [x] Code has been tested locally and passes all relevant tests.
- [x] Documentation has been updated to reflect the changes, if applicable.
- [x] Code follows the established coding style and guidelines of the project.
- [x] All new and existing tests related to the changes have passed.
- [x] Any necessary dependencies or new packages have been properly documented.
- [x] Pull request title and description are clear and descriptive.
- [x] Reviewers have been assigned to the pull request.
- [x] Any potential security implications have been considered and addressed.
- [x] Performance impact of the changes has been evaluated, if relevant.

## Notes for Reviewers

Security concerns:
- Passwords should have more strict requirements
- HTTPS should be used in the future

2023-10-03 10:13 UTC, Mafusn commented on eml/screens/errors/errorHandler.js
Are the three if statements with the variable 'something' inside supposed to be in the dev branch?

2023-10-03 10:15 UTC, Mafusn commented on eml/test/components/sum.js
Maybe just delete this file?

2023-10-03 10:16 UTC, Mafusn requested changes
Only got two comments

2023-10-03 19:09 UTC, Havkost requested changes
## Nice job
Would be nice to implement Montserrat as the default font before we merge into dev.
Super great work with the testing! :)

2023-10-04 10:06 UTC, Jatewo commented on eml/test/components/sum.js
Should already be deleted :)

2023-10-04 11:12 UTC, Havkost approved these changes
## Looks good, approving
We could still add a bit more testing for emails, but we need to agree 100% on the correct form of emails first. The regex file in assets is a good first step 👍

2023-10-04 13:06 UTC, merged

2023-10-05 12:03 UTC, TheMOHD3886 reviewed
ye