Gamified
Educado-App/educado-mobile pull request #48
Opened 2023-10-06 13:04 UTC by Mafusn

## Description

Briefly describe the purpose and context of this pull request.

This pull request includes the implementation of the following PBIs:

- [App Login] As non-logged in user, I want to have the ability to preview the app, so that I can understand the application before register/login
- [App Home] As a waste picker, I want to view when I don't have an active course (empty state)
- [App Profile] As a waste picker, I would like to be able to see and edit my profile, in order to see what personal information is connected to my profile and edit in case something is incorrect or not up to date
- [App Profile] As a waste-picker, I want to have the ability to delete my account

## Changes

- Delete user implemented
- Profile settings page created
- Implemented ability to update first name, last name and email
- Added a welcome screen
- Updated screen when the user has no active courses
- Unit tests made
- Cleanup in all touched files
- Updated some of the routes in api.js and userApi.js

## Related Issues

Deletion of user can end up not working, as it hasn’t been tested with a logged in user. The same applies to update of first name, last name and email.

## Checklist

- [ ] Code has been tested locally and passes all relevant tests.
- [ ] Documentation has been updated to reflect the changes, if applicable.
- [ ] Code follows the established coding style and guidelines of the project.
- [ ] All new and existing tests related to the changes have passed.
- [ ] Any necessary dependencies or new packages have been properly documented.
- [ ] Pull request title and description are clear and descriptive.
- [ ] Reviewers have been assigned to the pull request.
- [ ] Any potential security implications have been considered and addressed.
- [ ] Performance impact of the changes has been evaluated, if relevant.

## Screenshots (if applicable)
![Simulator_Screenshot_-_iPhone_15_Pro_-_2023-10-06_at_14 50 56](https://github.com/Educado-App/educado-mobile/assets/92912046/cda67326-c226-4888-84a8-a0cd5c9c7f72)
![Simulator_Screenshot_-_iPhone_15_Pro_-_2023-10-06_at_14 58 28](https://github.com/Educado-App/educado-mobile/assets/92912046/220ffacb-597b-4d01-bfee-9e1091174e9a)
![Simulator_Screenshot_-_iPhone_15_Pro_-_2023-10-06_at_14 55 48](https://github.com/Educado-App/educado-mobile/assets/92912046/0ddcf9df-75f9-4811-bc58-2505aa4990e0)

![Profile settings page](https://github.com/Educado-App/educado-mobile/assets/92912046/757b31bf-986a-4e9f-b789-e60e7572b53d)

## Notes for Reviewers

2023-10-06 14:29 UTC, Havkost requested changes
## Changes requested
Nice work, only got a few comments for the merge, keep at it.

2023-10-09 07:15 UTC, Jatewo commented on eml/App.js
> -  return isFontsLoaded() ? (
> Seems to me you've removed the isFontsLoaded check, is this on purpose?

I believe this is the only place where we actually need this check, so it probably shouldn't be removed

2023-10-09 08:15 UTC, Jatewo requested changes
Good work. I have some comments with changes requested and a few questions. Furthermore, in general, I'd like some comments/documentation in all files, which is also needed to adhere to our DoD. You are also missing quite a few tests as far as I can see. There seems to be several files without any tests made for them.

2023-10-09 08:15 UTC, Jatewo commented on eml/components/profileSettings/changeEmailButton.js
> +          Alert.alert('Alerta', 'Erro ao atualizar o e-mail, tente novamente: ', error.message);
+1

2023-10-09 08:15 UTC, Jatewo commented on eml/constants/Fonts.js
>      'Montserrat-Regular': require('../assets/fonts/Montserrat-Regular.ttf'),
We should probably have all the fonts in here, and also make sure they are defined in tailwind

2023-10-10 07:59 UTC, benceisonline commented on eml/App.js
> -  return isFontsLoaded() ? (
We do not need it in app.js, but in screens that use fonts.

2023-10-10 08:12 UTC, benceisonline commented on eml/components/loading/Loading.jsx
> +  if (!isFontsLoaded()) {
we get an error if we add isfontsloaded to app.js, and also if we remove from screens

2023-10-12 08:53 UTC, closed without merging