v_2 [Team Offline] created course and section screen
Educado-App/educado-mobile pull request #71
Opened 2023-10-18 19:38 UTC by sofiiagran

xxx This is an updated version from the former pull request

## Description

Added Course Screen and Section Screen

## Changes

Added two new screens:
- Course page where the user can view all their subscriptions
   Added progress bar
- Section page where the user can view all the sections for each course
   Added progress bar
   Added cancel subscription button

There is also added some new APIs, and all of them have been tested.

StorageServices is used to fetch the users subscriptions as well as all the section from a course.

There is also one for fetching all courses, but it is not in use now, because it is depended on explore page, the same goes for the subscribe functionality. The function are tested, but misses UI from other groups.

Added a unified way wrapper component/screen for insuring a consistent layout. These components is BaseScreen and IconHeader

## Related Issues

PBI: [App Course] As a waste picker i would like to see a unsubscribe button, when i want to leave a course.
PBI: [App Course] As a waste picker, I want to access all the course sections and and tap to start doing one of them
PBI: [App Home] As a waste picker, I want to view my subscribed courses

## Checklist

- [x] Code has been tested locally and passes all relevant tests.
- [x] Documentation has been updated to reflect the changes, if applicable.
- [x] Code follows the established coding style and guidelines of the project.
- [x] All new and existing tests related to the changes have passed.
- [x] Any necessary dependencies or new packages have been properly documented.
- [x] Pull request title and description are clear and descriptive.
- [x] Reviewers have been assigned to the pull request.
- [x] Any potential security implications have been considered and addressed.
- [x] Performance impact of the changes has been evaluated, if relevant.

## Screenshots (if applicable)

![Simulator Screenshot - iPhone 15 Pro Max - 2023-10-18 at 14 42 35](https://github.com/Educado-App/educado-mobile/assets/43484432/46db46fc-d819-4910-8db1-5ad52f44b06f)

![Simulator Screenshot - iPhone 15 Pro Max - 2023-10-18 at 14 42 52](https://github.com/Educado-App/educado-mobile/assets/43484432/7f8db3b3-a205-4d92-bc87-20184520f541)

![Simulator Screenshot - iPhone 15 Pro Max - 2023-10-18 at 14 43 00](https://github.com/Educado-App/educado-mobile/assets/43484432/1b864b86-fc9f-450c-bd14-0ce3b0ae3762)

![Simulator Screenshot - iPhone 15 Pro Max - 2023-10-18 at 14 43 18](https://github.com/Educado-App/educado-mobile/assets/43484432/b6bfec46-c1a2-4431-abca-f593bb3978a0)

![Simulator Screenshot - iPhone 15 Pro Max - 2023-10-18 at 14 45 26](https://github.com/Educado-App/educado-mobile/assets/43484432/207289d6-54ed-4da8-84d8-3ef37b6dbf3f)

## Notes for Reviewers

2023-10-19 08:08 UTC, TheMOHD3886 approved these changes
I skimmed through it and it looked fine, good work 👍

2023-10-19 08:10 UTC, Havkost requested changes
## Changes requested

Great job, nice that there are so many tests, just got a few comments.

2023-10-19 08:16 UTC, JackSMunn commented on eml/assets/logo.svg
If you are not using it, delete it

2023-10-19 08:17 UTC, JackSMunn commented on eml/components/general/BaseScreen.js
> +        <View className="flex-1 bg-[#f1f9fb]">
+1

2023-10-19 08:24 UTC, PrometheusBork commented on eml/assets/logo.svg
We actually do not use this logo, so we can remove it if necessary.

2023-10-19 08:45 UTC, ITPini commented on eml/components/general/BaseScreen.js
> +        <View className="flex-1 bg-[#f1f9fb]">
commit 8b3ac87fd5e27e8f3cb6364918c255d092d6e4d9 have solved this issue by using `bg-secondary` instead of `bg-[#f1f9fb]`

2023-10-19 09:04 UTC, loui981c requested changes
der er lidt små ting her og der, men it lookie very nice

2023-10-19 09:04 UTC, loui981c commented on eml/services/StorageService.js
> +    throw new Error("Error getting course list from async storage: " + error.message)
burde throw ikke være inde i try catch?

2023-10-19 09:07 UTC, sofiiagran commented on eml/screens/courses/CourseScreen.jsx
> +    useEffect(() => {
however if we do not use it, it does not refresh when user subscribe to new courses, do you have a better solution? @Havkost

2023-10-19 09:07 UTC, sofiiagran commented on eml/test/api/api.test.js
@Havkost should I make localhost as variable, so we can change it when we deploy?

2023-10-19 09:10 UTC, PrometheusBork commented on eml/components/section/SectionCard.jsx
> +        navigation.navigate('HomeStack'); // Replace with the name of the target screen
Skal i virkeligheden navigere til et tilhørende exercise, men det er ikke helt muligt da exercises ikke er implementeret endnu

2023-10-19 09:30 UTC, ITPini commented on eml/assets/logo.svg
commit a53c4a3d1548c9d3b5c551d505e96b34079b0bf7 have solved this issue by removing this file.

2023-10-19 10:58 UTC, ITPini commented on eml/components/courses/courseCard/CourseCard.jsx
> +                        <MaterialCommunityIcons size={28} name="play-circle" color={'#5ECCE9'}></MaterialCommunityIcons>
commit b65ca53e107ef3bb422f203832c880bba9605bbe have solved this issue by placing various hardcoded colors with colors from Tailwind config

2023-10-19 12:01 UTC, ITPini commented on eml/components/section/SectionCard.jsx
> +        <View className="bg-transparent m-[2.2%] rounded-[10px] shadow-[0px 2px 4.65px #000] shadow-opacity-[0.3]">
commit 83a8b826ffcf8096e13fe56921d21519819bfd7b have resolved this issue by updating various Tailwind styles

2023-10-19 12:08 UTC, sofiiagran commented
Console.log removed.

All communication with AsyncStorage is moved to StorageServices: api.js and StorageServices.js are therefore edited and new tests are added.

In api.test.js hardcoded localhost:8888 is changed to a port variable and can be changed when deployment.

Hardcoded colours are not hardcoded anymore and follows the stylesheet.

Simplified styling 

We have decided to keep useEffect until we find a better solution

2023-10-19 12:23 UTC, sofiiagran commented
NB: new update, useEffect is no longer infinite loop

2023-10-19 14:29 UTC, JackSMunn requested changes
GJ nice code, LETS GOOOOO 🦺 🦅 

To quote Sofia "I PROMISE I WILL FIX THE ERRORS, PLEASE DONT HOLD THE PULL REQUEST BACK"  -> So the errors I will let slide.

So I will not request changes, but instead let it be up to her conscious how large the technical debt should become.

2023-10-19 14:29 UTC, JackSMunn commented on eml/services/StorageService.js
> +      throw new Error("Error getting course from database: " + error.message)
Same here regarding errors.

2023-10-19 14:29 UTC, JackSMunn commented on eml/services/StorageService.js
> +    throw new Error("Error getting course list from async storage: " + error.message)
Same here regarding errors.

2023-10-19 18:28 UTC, ITPini commented on eml/components/section/SectionCard.jsx
> +    const backgroundColor = isComplete ? "bg-[#87eb8e]" : inProgress ? "bg-[#87CEEB]" : notPossible ? "bg-[#F20000]" : {};
commit 333def19e73c2640d014877d94142665209e892d have solved this issue by replacing hardcoded colors with colors from Tailwind config

2023-10-19 21:13 UTC, sofiiagran commented
Ready for re-review by @JackSMunn and @Havkost, all mock data is now moved to separate files. 

I could not find the file where one could find the error codes (for mobile). however, since this is not crucial, I really hope that you can still approve the code so that we will have it in dev (and staging) before the sprint review on Monday. 

The error codes will be fixed in next week (probably Monday or Tuesday)¨

thank you:))

2023-10-19 21:25 UTC, Havkost approved these changes
## Approved

Great job guys, seems to me all my requested changes have been fixed.
We need to keep an eye on the URL used in the api test, as that will be deprecated once we move from a hardcoded value, into an environment file.

I was unable to see any courses when I logged in to the ola.lola@mail.dk using the production database. As such I haven't seen the code actually working on my machine, please test this with others before you merge :)

2023-10-20 07:16 UTC, JackSMunn approved these changes

2023-10-20 10:00 UTC, Jatewo requested changes
### Great work overall
I have a few requests for changes. See my comments for these. Feel free to ask if you have any questions 👍

2023-10-20 10:12 UTC, JackSMunn approved these changes
I approve on the basis that I (me, singular person) is okay with the promise that the errors will be reworked first thing next sprint. However if some are not happy with it, then  it should be fixed.

## Big note ##

I can't run this. 4 other people can, but i cannot.

2023-10-20 10:51 UTC, ITPini commented on eml/assets/sectionThumbnail.png
commit 213e0e3e475ad895850e980bae8978584f327543 resolved this issue by moving `eml/assets/sectionThumbnail.png` to `eml/assets/images/sectionThumbnail.png`

2023-10-20 10:53 UTC, sofiiagran commented
@Jatewo we are ready for re-review, addressed all comments

2023-10-20 12:00 UTC, merged